### ISSUE TITLE
Installation Instructions Minor issues

### ISSUE THREAD

**Issue by arriflex** [flightaware/fa-grafana#1]
Following the "Setup" outlined in README.md on a fresh PiAware install modified only with ssh enabled, user pi's password changed and my public key uploaded I found the following issues: 

1. No problems aside from a warning: apt-key output should not be parsed (stdout is not a terminal)
2. `pi@piaware:/ $ git clone https://github.com/flightaware/fa-grafana.git`
`fatal: could not create work tree dir 'fa-grafana': Permission denied`
Using sudo to checkout the repository succeeded in creating the new directory.
3. .env is unwritable unless escalating privilege again using sudo

Thanks for putting this together, the containers spun up properly without further issue. I love Grafana!

**Comment by eric1tran** [comment]
It looks like you are trying to git clone into the root directory (pi@piaware:/) . Enter `cd` to get to your home directory and it should work from there.

And no problem! I plan to get back to this to add more features whenever I can find the time.

**Comment by arriflex** [comment]
Super, I figured I was doing something wrong. I should have started in my home directory, thanks! It may be helpful to either add a directory change to the end of the bash script for noobs like myself or just remind us via the readme.
